name                = "axion-pad"
pages_build_output_dir = ".vercel/output/static"
compatibility_date  = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding       = "DB"            # must match env.d.ts CloudflareEnv.DB
database_name = "axionpad-db"
database_id   = "f62ca889-9221-4ba5-9980-185b588997be"